### ISSUE TITLE
Passenger Error

### ISSUE THREAD

**Issue by cowboycodur** [stpl/redmine_wysiwyg#1]
After bundle install
# bundle install --without development test

Using RedCloth 3.0.4
Using execjs 2.0.2
Using libv8 3.11.8.17
Using ref 1.0.5
Using therubyracer 0.11.4
Using bundler 1.6.1
Your bundle is complete!
Gems in the groups development and test were not installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

Receive this trace...

cannot load such file -- redcloth (LoadError)
  /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:251:in `require'
  /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:251:in`block in require'
  /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:236:in `load_dependency'
  /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:251:in`require'
  /usr/share/redmine/lib/plugins/redmine_wysiwyg/init.rb:3:in `block in <top (required)>'
  /usr/share/redmine/config/initializers/00-core_plugins.rb:12:in`eval'
  /usr/share/redmine/config/initializers/00-core_plugins.rb:12:in `block in <top (required)>'
  /usr/share/redmine/config/initializers/00-core_plugins.rb:2:in`each'
  /usr/share/redmine/config/initializers/00-core_plugins.rb:2:in `<top (required)>'
  /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:245:in`load'
  /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:245:in `block in load'
  /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:236:in`load_dependency'
  /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:245:in `load'
  /usr/lib/ruby/vendor_ruby/rails/engine.rb:593:in`block (2 levels) in class:Engine'
  /usr/lib/ruby/vendor_ruby/rails/engine.rb:592:in `each'
  /usr/lib/ruby/vendor_ruby/rails/engine.rb:592:in`block in class:Engine'
  /usr/lib/ruby/vendor_ruby/rails/initializable.rb:30:in `instance_exec'
  /usr/lib/ruby/vendor_ruby/rails/initializable.rb:30:in`run'
  /usr/lib/ruby/vendor_ruby/rails/initializable.rb:55:in `block in run_initializers'
  /usr/lib/ruby/vendor_ruby/rails/initializable.rb:54:in`each'
  /usr/lib/ruby/vendor_ruby/rails/initializable.rb:54:in `run_initializers'
  /usr/lib/ruby/vendor_ruby/rails/application.rb:136:in`initialize!'
  /usr/lib/ruby/vendor_ruby/rails/railtie/configurable.rb:30:in `method_missing'
  /usr/share/redmine/config/environment.rb:14:in`<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in`block in <main>'
  /usr/lib/ruby/vendor_ruby/rack/builder.rb:51:in `instance_eval'
  /usr/lib/ruby/vendor_ruby/rack/builder.rb:51:in`initialize'
  config.ru:1:in `new'
  config.ru:1:in`<main>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:112:in `eval'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:112:in`preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:158:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in`module:PhusionPassenger'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:28:in `<main>'

**Comment by stpl** [comment]
Have tested this with Apach and Phusion passenger. It is working properly.

Please provide more information to debug this.
